import path from "node:path";
import { test, expect, devices, type BrowserContext, type Page } from "@playwright/test";

/**
 * End-to-end coverage of the Read surface's PDF-ingestion mode
 * (AddContentForm's "PDF" segment -> multipart POST /api/content, see
 * src/server/pdf.ts). Uploads fixtures/articulo-es-mx.pdf (generated by
 * scripts/make-fixture-pdf.mjs from fixtures/article-es-mx.txt, deliberately
 * hard-wrapped with at least one line-wrap hyphenation) and confirms the
 * whole pipeline — extractPdfText -> cleanPdfText -> extraction -> capture
 * loop — works end to end.
 *
 * Which fixture-provider extraction path this hits is not incidental to the
 * test: because cleanPdfText reconstructs the fixture PDF's text as a
 * byte-for-byte match of fixtures/article-es-mx.txt (verified in
 * src/server/pdf.test.ts), FixtureProvider's canned-match check
 * (`req.user.includes(firstSentence(articleText))`, src/server/language/
 * providers/fixture.ts) fires, and extraction returns the SAME canned
 * 10-candidate result read-flow.spec.ts exercises against the seeded
 * article — confirmed by a live curl run against this exact fixture during
 * development. So this spec asserts on that canned shape (>=8 marks, a
 * "0/10" counter) rather than the looser synthetic-path assertions, the same
 * way read-flow.spec.ts does for the seeded article.
 *
 * Same idiom as read-flow.spec.ts: one `describe.serial` sharing a single
 * page/context, Pixel 7 device, against the shared e2e webServer/db.
 */

const FIXTURE_PDF = path.join(process.cwd(), "fixtures", "articulo-es-mx.pdf");
const PDF_TITLE = "Café de especialidad (PDF de prueba)";

const SCANNED_FIXTURE_PDF = path.join(process.cwd(), "fixtures", "escaneo-es-mx.pdf");
const SCANNED_PDF_TITLE = "Café de especialidad (escaneo de prueba)";

test.describe.serial("Read PDF ingestion", () => {
  let context: BrowserContext;
  let page: Page;
  let contentId: string;
  let firstCandidateId: string;

  test.beforeAll(async ({ browser }, testInfo) => {
    context = await browser.newContext({
      ...devices["Pixel 7"],
      baseURL: testInfo.project.use.baseURL,
    });
    page = await context.newPage();
  });

  test.afterAll(async () => {
    await context.close();
  });

  test("1. uploading a PDF via the add form lands on the reader with highlights", async () => {
    await page.goto("/add");
    await page.getByRole("button", { name: "PDF" }).click();

    await expect(page.getByLabel("Archivo PDF")).toBeVisible();
    await page.getByLabel("Archivo PDF").setInputFiles(FIXTURE_PDF);

    await page.getByRole("button", { name: "Agregar contenido" }).click();

    await page.waitForURL(/\/read\//, { timeout: 30_000 });
    contentId = new URL(page.url()).pathname.split("/").filter(Boolean).pop()!;
    expect(contentId.length).toBeGreaterThan(0);

    // Confirms the PDF's own Title metadata (extractPdfText) made it onto
    // the content row, not just a generic fallback.
    await expect(page.getByRole("heading", { name: PDF_TITLE })).toBeVisible();

    const marks = page.locator('article [data-testid="candidate-mark"]');
    await expect(marks.first()).toBeVisible({ timeout: 15_000 });
    expect(await marks.count()).toBeGreaterThanOrEqual(8);

    await expect(page.getByTestId("decision-counter")).toHaveText("0/10");
  });

  test("2. the cleaned PDF text reconstructed a known phrase spanning the fixture's forced line-wrap hyphenation", async () => {
    const res = await page.request.get(`/api/content/${contentId}`);
    expect(res.ok()).toBe(true);
    const body = (await res.json()) as { content: { text: string } };

    // "tostadores" is the word scripts/make-fixture-pdf.mjs forces a
    // line-wrap hyphenation across ("tostad-" / "ores") — if cleanPdfText's
    // de-hyphenation regressed, this substring would read "tostad- ores" or
    // "tostad-ores" instead.
    expect(body.content.text).toContain("tostadores mexicanos");
    expect(body.content.text).not.toMatch(/tostad-/);
  });

  test("3. keeping a candidate persists the decision", async () => {
    const marks = page.locator('article [data-testid="candidate-mark"]');
    firstCandidateId = (await marks.first().getAttribute("data-candidate-id"))!;
    expect(firstCandidateId).toBeTruthy();

    await marks.first().click();

    const sheet = page.getByTestId("candidate-sheet");
    await expect(sheet).toBeVisible();
    await sheet.getByRole("button", { name: "Guardar" }).click();

    await expect(page.getByTestId("decision-counter")).toHaveText("1/10");

    const firstMark = page.locator(`[data-candidate-id="${firstCandidateId}"][data-testid="candidate-mark"]`);
    await expect(firstMark).toHaveAttribute("data-state", "keep");
  });

  test("4. reloading the page keeps the decision", async () => {
    await page.reload();

    const firstMark = page.locator(`[data-candidate-id="${firstCandidateId}"][data-testid="candidate-mark"]`);
    await expect(firstMark).toHaveAttribute("data-state", "keep");
    await expect(page.getByTestId("decision-counter")).toHaveText("1/10");
  });

  test("5. cleanup: review the captured item away so it doesn't crowd out review-flow.spec.ts's due-item chips", async () => {
    // Test hygiene, not app behavior under test: this suite shares one DB
    // across every spec file (see review-flow.spec.ts's file doc comment),
    // and /fix/write's Reto mode only shows the top RETO_CHIP_COUNT (6) due
    // items (src/components/FixComposer.tsx), earliest-due first. Left
    // freshly-captured (and thus "due"), the item from test 3 above sorts
    // ahead of review-flow.spec.ts's own items (captured later, since
    // read-pdf.spec.ts runs first alphabetically) and can crowd them out of
    // that top-6 window. Rating it here removes it from the due pool without
    // touching the `captured` decision itself (decisions are derived from
    // captured/discarded events, never from `reviewed` events — see
    // getDecisions in src/server/repo.ts), so test 4's assertions above are
    // unaffected.
    const recentRes = await page.request.get("/api/items/recent?limit=1");
    expect(recentRes.ok()).toBe(true);
    const { items } = (await recentRes.json()) as { items: { id: string }[] };
    expect(items.length).toBe(1);

    const reviewRes = await page.request.post("/api/reviews", {
      data: { itemId: items[0].id, rating: "easy" },
    });
    expect(reviewRes.ok()).toBe(true);
  });
});

/**
 * End-to-end coverage of the OCR fallback (src/server/pdf.ts): uploading a
 * scanned/image-only PDF (fixtures/escaneo-es-mx.pdf, generated by
 * scripts/make-fixture-scanned-pdf.mjs — no text layer at all, every page a
 * full-bleed PNG raster) still lands the learner on a readable, highlighted
 * reader page instead of a 422.
 *
 * Deliberately does NOT assert on a specific candidate count or byte-match
 * the canned extraction fixture the way the text-layer suite above does:
 * OCR's reconstructed text is not guaranteed to be byte-identical to
 * fixtures/article-es-mx.txt run to run, so FixtureProvider's exact-substring
 * canned-match check (see src/server/language/providers/fixture.ts) may or
 * may not fire — this suite only requires that *some* candidates were
 * extracted (the synthetic fallback path always produces at least one from
 * any input with a real sentence in it) and doesn't touch decisions, so it
 * adds no `captured`/`reviewed` state for later specs to worry about.
 *
 * OCR is slow relative to the rest of this suite (seconds per page, real
 * CPU-bound WASM recognition, not a network mock) — this file's one test
 * gets a generous timeout rather than the config default.
 */
test.describe.serial("Read scanned PDF ingestion (OCR fallback)", () => {
  let context: BrowserContext;
  let page: Page;

  test.beforeAll(async ({ browser }, testInfo) => {
    context = await browser.newContext({
      ...devices["Pixel 7"],
      baseURL: testInfo.project.use.baseURL,
    });
    page = await context.newPage();
  });

  test.afterAll(async () => {
    await context.close();
  });

  test("uploading a scanned (text-layer-free) PDF shows the longer-wait copy, then lands on the reader with highlights", async () => {
    test.setTimeout(120_000);

    await page.goto("/add");
    await page.getByRole("button", { name: "PDF" }).click();

    await expect(page.getByLabel("Archivo PDF")).toBeVisible();
    await page.getByLabel("Archivo PDF").setInputFiles(SCANNED_FIXTURE_PDF);

    await page.getByRole("button", { name: "Agregar contenido" }).click();

    // The honest "this takes longer" pending copy (src/components/AddContentForm.tsx)
    // should be visible while OCR runs, before the reader shows up.
    await expect(page.getByRole("button", { name: /los escaneos tardan más/ })).toBeVisible();

    await page.waitForURL(/\/read\//, { timeout: 90_000 });

    // Confirms OCR extracted the scanned PDF's own Title metadata, same as
    // the text-layer path.
    await expect(page.getByRole("heading", { name: SCANNED_PDF_TITLE })).toBeVisible();

    const marks = page.locator('article [data-testid="candidate-mark"]');
    await expect(marks.first()).toBeVisible({ timeout: 15_000 });
    expect(await marks.count()).toBeGreaterThanOrEqual(1);
  });
});
